### ISSUE TITLE
Fix handshake table on Mobile

### ISSUE THREAD

**Issue by plegner** [mathigon/textbooks#10]
The handshake table in [Graphs and Networks](https://mathigon.org/course/graphs-and-networks#handshakes-2) is broken on mobile devices:

![](https://user-images.githubusercontent.com/2439570/39084775-02040396-4572-11e8-80e3-74dc80c12a65.png)

**Comment by WilliamOConnell** [comment]
Made a [PR](https://github.com/mathigon/textbooks/pull/25) to resolve this.
