### ISSUE TITLE
Prevent cheating in Königsberg Bridges

### ISSUE THREAD

**Issue by plegner** [mathigon/textbooks#11]
For the Königsberg Bridges problem in [Graphs and Networks](https://mathigon.org/course/graphs-and-networks#bridges), you can cheat by moving the cursor outside the city area:

<img width="774" alt="screen shot 2018-04-21 at 14 42 48" src="https://user-images.githubusercontent.com/2439570/39084798-47c0dfc6-4572-11e8-82ae-fbcfc10fa247.png">

**Comment by plegner** [comment]
Fixed in https://github.com/mathigon/textbooks/commit/6c882cbcf55c609a6d26e48436c385eb3cad620a

(Although the `pointerenter` and `pointerleave` events could use a lot more cleanup work…)

**Comment by DegrangeM** [comment]
Still possible with scrolling, and probably with zooming too.

![image](https://user-images.githubusercontent.com/53106394/69925558-1a3a0b80-14b1-11ea-9da3-5b1fe4ad2a3d.png)

But it's probably a bad idea to try to fix that.

**Comment by plegner** [comment]
Fixed in https://github.com/mathigon/textbooks/commit/34900982c7e243d40caa4d678dc6513c74c180df by forcing a stop event whenever you start scrolling or zooming.

**Comment by DegrangeM** [comment]
Still possible with right click ;)

**Comment by DegrangeM** [comment]
It is also possible to cheat by spamming left click while moving over little distance. This allow to cross water.

![image](https://user-images.githubusercontent.com/53106394/69981205-21552e00-1532-11ea-96df-316faaa8e7ea.png)
