### ISSUE TITLE
machine translation should be indicated

### ISSUE THREAD

**Issue by matheharry** [mathigon/textbooks#156]
I believe that machine translation should be used with caution in the texts on mathematical topics, because mathematical terms are rarely used correctly. At least in the German translation, they may cause more harm than good to the pupils and students.
Therefore it would be absolutely necessary to mark these translations as machine translations which should be used with caution.

**Comment by plegner** [comment]
Great idea – I'll add that in a future update!

**Comment by plegner** [comment]
Fixed in the next release:
<img width="936" alt="Screenshot 2020-07-15 at 20 31 27" src="https://user-images.githubusercontent.com/2439570/87584598-0957a680-c6de-11ea-996b-b7cb0ffa5d90.png">

**Comment by matheharry** [comment]
👍 Wow, that was fast!

**Comment by jsuccari** [comment]
@Philipp Legner <philipp@mathigon.org> Even though folks are reviewing the
auto-translations; it's a nice idea!!! Quickest bug fixer in town! :-)
