### ISSUE TITLE
Fix Ulam Spiral diagram on mobile

### ISSUE THREAD

**Issue by plegner** [mathigon/textbooks#19]
See https://mathigon.org/course/divisibility-and-primes#ulam

The diagram is currently broken on mobile:
<img width="416" alt="screen shot 2018-04-25 at 12 37 44" src="https://user-images.githubusercontent.com/2439570/39243479-78ddb230-4885-11e8-8b4e-ec48e5168057.png">
vs
<img width="366" alt="screen shot 2018-04-25 at 12 37 39" src="https://user-images.githubusercontent.com/2439570/39243486-7c95a216-4885-11e8-844c-17730372e5b5.png">

**Comment by WilliamOConnell** [comment]
[Fixed](https://github.com/mathigon/textbooks/pull/27) by changing the max-width at the same breakpoints that change the cell size, although this type of layout might be better implemented with a table or CSS grids or something.

![](https://s3.amazonaws.com/sharex.williamoconnell/MLJwJ6r5kiTD.png)

**Comment by plegner** [comment]
I definitely agree that CSS grid might be more appropriate here – but this seems to work for now. Thanks!
