### ISSUE TITLE
Typo in timeline

### ISSUE THREAD

**Issue by lostinthelights** [mathigon/textbooks#226]
Claude Shannon's lifetime is (1916 - 2001) according to Wikipedia. But in timeline activity of Mathigon, both on website and Android app it mentions (1898 – 1972).

**Comment by plegner** [comment]
Thanks for reporting this! Fixed in https://github.com/mathigon/textbooks/commit/af9b6e535fca8aeab9c68db0d23a2fa90f9c6493
