### ISSUE TITLE
Add a license to the GitHub repository

### ISSUE THREAD

**Issue by dbieber** [mathigon/textbooks#26]
Hi, Would it be possible for you to add a LICENSE file to the GitHub repository, e.g. with the text of the MIT or Apache 2 license (or whatever license you choose, of course)? This makes it easier for employees at companies such as Google to sign the CLA and contribute.

**Comment by plegner** [comment]
That's a great suggestion – I will definitely look into this, but unfortunately, this repo also contains a lot of content that doesn't have an open license (e.g. illustrations or video clips). Something like "Creative Commons" might be more appropriate…

**Comment by DegrangeM** [comment]
A first step might be to put textbooks text files under MIT (content.md, function.ts, styles.less,hints.yaml and concepts.yaml).

**Comment by justjosias** [comment]
It would be good to put a license on this repository. Maybe CC-BY (or CC-BY-SA) for the content, and MIT for the code. Proprietary artwork can be marked as such (if you can't license them freely). You just need to make the license file specify that.

This would enable schools to customize the software to their needs and encourage contribution.

What do you think?

**Comment by plegner** [comment]
Thanks for your feedback – however, at this time, we have no plans to release our content under an open license, or allow third-parties to modify and re-distribute it.

All of the content will remain freely available at https://mathigon.org, and the underlying JavaScript libraries all have an MIT license (see https://mathigon.io)
