### ISSUE TITLE
Completion of exercise on Congruence is not detected 

### ISSUE THREAD

**Issue by yannickmoy** [mathigon/textbooks#328]
In the course on Euclid's Axioms, the section on Congruence does not automatically display the next batch of text after the exercises is completed, which looks like a bug.

The workaround is for the user to click on the message "Are you stuck? Skip to the next step or reveal all steps"

**Comment by plegner** [comment]
Unable to reproduce this. Note that the 3 ellipses have to be connected in a triangle
