### ISSUE TITLE
Directed graph glossary

### ISSUE THREAD

**Issue by DegrangeM** [mathigon/textbooks#64]
I am working on the french translation of the glossary.

> In a directed graph, every edge as an arrow, i.e. a start vertex and an end vertex.

Is it a correct english sentence ? I understand the meaning of the sentence (so I can translate it) but it doesn't seems correct in english. However I might be wrong as english is not my main language.

**Comment by plegner** [comment]
Thanks, @DegrangeM – yes, it should be "has" instead of "as". Fixed in https://github.com/mathigon/textbooks/commit/42bbfd56a3b6130bcbe6f0a540c4f26a3432b383
