### ISSUE TITLE
minor typo in glossary.yaml [ polyhedron ]

### ISSUE THREAD

**Issue by jsuccari** [mathigon/textbooks#87]
polyhedron:
  title: Polyhedron
  text: A __polyhedron__ (the plural is _polyhedra_) is a 3-dimensional solid
    with no **curves** surfaces or edges. All faces of a polyhedron are polygons.
    For example, a cube and a pyramid are polyhedra, but a sphere is not.
  link: /course/polyhedra/polyhedra

should read as follows:

polyhedron:
  title: Polyhedron
text: A __polyhedron__ (the plural is _polyhedra_) is a 3-dimensional solid
    with no **curved** surfaces or edges. All faces of a polyhedron are polygons.
    For example, a cube and a pyramid are polyhedra, but a sphere is not.
  link: /course/polyhedra/polyhedra

**Comment by jsuccari** [comment]
aleph-zero:
  title: Aleph Zero
  text: Aleph Zero, written using the Hebrew letter א‎, is the cardinality of
    a countably infinite set (e.g. the **natual** numbers).

should read as follows:

aleph-zero:
  title: Aleph Zero
  text: Aleph Zero, written using the Hebrew letter א‎, is the cardinality of
    a countably infinite set (e.g. the **natural** numbers).

coordinate-system:
  title: Coordinate System
  text: A __cordinate sytem__ is a 2-dimensional plane that contains two
    perpendicular axes. Every point on the plane can be defined using two
     .....

should read as follows:

coordinate-system:
  title: Coordinate System
  text: A **__coordinate sytem__** is a 2-dimensional plane that contains two
    perpendicular axes. Every point on the plane can be defined using two
     

hypotenuse:
  title: Hypotenuse
  text: The __hypotenuse__ of a right-angled triangle is its longest side, which
    lies **oppsite** the right angle.
  image: right-triangle.svg

should read as follows:

hypotenuse:
  title: Hypotenuse
  text: The __hypotenuse__ of a right-angled triangle is its longest side, which
    lies **opposite** the right angle.
  image: right-triangle.svg

imaginary:
  title: Imaginary Numbers
  text: |
    __Imaginary numbers__ are generated by taking square roots of negative
    numbers. **despite** their name, they are of great importance in mathematics,
    science and engineering. ....

should read as follows:

imaginary:
  title: Imaginary Numbers
  text: |
    __Imaginary numbers__ are generated by taking square roots of negative
    numbers. **Despite** their name, they are of great importance in mathematics,
    science and engineering. ...

infinity:
  title: Infinity
  text: __Infinity__ is a quantity without limit or end. In **matematics**, it is
    represented by the symbol `∞`.

should read as follows:

infinity:
  title: Infinity
  text: __Infinity__ is a quantity without limit or end. In **mathematics**, it is
    represented by the symbol `∞`.

parabola-vertex:
  title: Vertex of a Parabola
  text: The __vertex__ of a parabola is the point at which it changes direction.
    It is either the maximum or the **mimum** of the corresponding quadratic
    function, and it lies on the axis of symmetry of the parabola.
  # The vertex is halfway between the directrix and the focus of the parabola.

should read as follows:

parabola-vertex:
  title: Vertex of a Parabola
  text: The __vertex__ of a parabola is the point at which it changes direction.
    It is either the maximum or the **minimum** of the corresponding quadratic
    function, and it lies on the axis of symmetry of the parabola.
  # The vertex is halfway between the directrix and the focus of the parabola.

protein:
  title: Protein
  text: |
    A __Protein__ is a large _macromolecule_ that can **perfom** many different
    functions within living organisms: from digestion to communicating between
    cells or replicating DNA. Proteins consist of one or more chains of _amino
    acid residues_.

should read as follows:

protein:
  title: Protein
  text: |
    A __Protein__ is a large _macromolecule_ that can **perform** many different
    functions within living organisms: from digestion to communicating between
    cells or replicating DNA. Proteins consist of one or more chains of _amino
    acid residues_.

There are a few more I'll add shortly

**Comment by plegner** [comment]
Thanks @jsuccari!
Fixed in https://github.com/mathigon/textbooks/commit/b9279ead099641353586d43bce070fb84c048fb6
