### ISSUE TITLE
A few more typos in the glossary

### ISSUE THREAD

**Issue by jsuccari** [mathigon/textbooks#88]
sieve-eratosthenes:
  title: Sieve of Eratosthenes
  text: The __Sieve of Eratosthenes__ is a procedure for finding prime numbers,
    by **continuoulsy** eliminating numbers that are _not_ prime.
  link: /course/divisibility/primes#eratosthenes

should read as follows:

sieve-eratosthenes:
  title: Sieve of Eratosthenes
  text: The __Sieve of Eratosthenes__ is a procedure for finding prime numbers,
    by **continuously** eliminating numbers that are _not_ prime.
  link: /course/divisibility/primes#eratosthenes

venn-diagram:
  title: Venn Diagram
  text: A **__venn** diagram__ visualises multiple properties or events that
    overlap.
  image: venn.svg

should read as follows:

venn-diagram:
  title: Venn Diagram
  text: A **__Venn** diagram__ visualises multiple properties or events that
    overlap.
  image: venn.svg

Sorry for not including these in the other issue that has been fixed.

**Comment by plegner** [comment]
Fixed in https://github.com/mathigon/textbooks/commit/c0ab112128d494f71ee42f7ca2e489704ef4ece1#diff-94ed24b170ed49ea63fcd992a6eb2767. Thanks!
