### ISSUE TITLE
typos in bios.yaml

### ISSUE THREAD

**Issue by jsuccari** [mathigon/textbooks#90]
al-haytham:
  born: 965
  died: 1050
  name: Al-Haytham
  bio: |
    __Hasan Ibn al-Haytham__ (أبو علي، الحسن بن الحسن بن الهيثم, c. 965 – 1050)
    lived in Cairo during the Islamic Golden Age, and studied mathematics,
    physics, astronomy, philosophy **and** medicine. He was a proponent of the
    _scientific method_: the belief that **any a** scientific hypothesis must be
    verified using experiments or mathematical logic – centuries before
    European scientists during the Renaissance. ...

should read as follows:

al-haytham:
  born: 965
  died: 1050
  name: Al-Haytham
  bio: |
    __Hasan Ibn al-Haytham__ (أبو علي، الحسن بن الحسن بن الهيثم, c. 965 – 1050)
    lived in Cairo during the Islamic Golden Age, and studied mathematics,
    physics, astronomy, philosophy **, and** medicine. He was a proponent of the
    _scientific method_: the belief that **any** a scientific hypothesis must be
    verified using experiments or mathematical logic – centuries before
    European scientists during the Renaissance.

al-karaji:
  born: 953
  died: 1029
  name: Al-Karaji
  bio: __Muhammad Al-Karaji__ (ابو بکر محمد بن الحسن الکرجی, c. 953 – 1029) was
    a Persian mathematician and engineer. He was the first person to use _**prove**
    by induction_, which allowed him to prove the binomial theorem.
  links:
    - title: Proof by Induction
      url: /world/Axioms_and_Proof

Should read as follows:

al-karaji:
  born: 953
  died: 1029
  name: Al-Karaji
  bio: __Muhammad Al-Karaji__ (ابو بکر محمد بن الحسن الکرجی, c. 953 – 1029) was
    a Persian mathematician and engineer. He was the first person to use _**proof**
    by induction_, which allowed him to prove the binomial theorem.
  links:
    - title: Proof by Induction
      url: /world/Axioms_and_Proof

al-khwarizmi:
  born: 780
  died: 850
  name: Al-Khwarizmi
  overflow: true
  bio: |
    The Persian mathematician __Muhammad Al-Khwarizmi__ (محمد بن موسى الخوارزمي‎,
    780 – 850) lived during the golden age of the Muslim Abbasid regime in
    Baghdad. He worked at the “House of Wisdom”, which contained the first large
    collection of academic books since the destruction of the Library of
    Alexandria.

    Al-Khwarizmi has been called the “**father** of algebra” – in fact, the word

Should read as follows:

al-khwarizmi:
  born: 780
  died: 850
  name: Al-Khwarizmi
  overflow: true
  bio: |
    The Persian mathematician __Muhammad Al-Khwarizmi__ (محمد بن موسى الخوارزمي‎,
    780 – 850) lived during the golden age of the Muslim Abbasid regime in
    Baghdad. He worked at the “House of Wisdom”, which contained the first large
    collection of academic books since the destruction of the Library of
    Alexandria.

    Al-Khwarizmi has been called the “**Father** of algebra” – in fact, the word

**This one comes up a lot. "Father of ....". In some cases, "Father is capitalized. IN other cases, it without quotes. Not sure if you want to standardize on a style. 

It comes up with:**

1. Al-Khwarizmi
2. Aristotle
3. Babbage
4. Democritus
5. Desargues
6. Descartes
7. Euclid
8. Galileo
9. Monge
10. Shannon
11. Turing

Other typos:

cardano:
  born: 1501
  died: 1576
  name: Cardano
  bio: |
    The Italian __Gerolamo Cardano__ (1501 – 1576) was one of the most
    influential mathematicians and scientists of the Renaissance. He
    investigated hypocycloids, published Tartaglia’s and Ferrari’s solution for
    cubic and quartic equations, was the first European to systematically use
    negative numbers, and even acknowledged the **existing** of imaginary numbers
    (based on `sqrt(-1)`).

    Cardano also made some early progress in probability theory and introduced binomial coefficients and binomial theorem to Europe. He invented many
    mechanical devices, including combination locks, gyroscopes with three
    degrees of freedom, and drive shafts (or Cardan shafts) that are still used
    in vehicles today.
  links:
    - title: Imaginary Numbers
      url: /world/Real_Irrational_Imaginary

Should read as follows:

cardano:
  born: 1501
  died: 1576
  name: Cardano
  bio: |
    The Italian __Gerolamo Cardano__ (1501 – 1576) was one of the most
    influential mathematicians and scientists of the Renaissance. He
    investigated hypercycloids, published Tartaglia’s and Ferrari’s solution for
    cubic and quartic equations, was the first European to systematically use
    negative numbers, and even acknowledged the **existence** of imaginary numbers
    (based on `sqrt(-1)`).

    Cardano also made some early progress in probability theory and introduced
    binomial coefficients and **the** binomial theorem to Europe. He invented many mechanical devices, including combination locks, gyroscopes with three degrees of freedom, and drive shafts (or Cardan shafts) that are still used in vehicles today.
  links:
    - title: Imaginary Numbers
      url: /world/Real_Irrational_Imaginary

cauchy:
  born: 1789
  died: 1857
  name: Cauchy
  small: true
  bio: |
    __Augustin-Louis Cauchy__ (1789 – 1857) was a French mathematician and physicist. He contributed to a wide range of areas in mathematics, and
    dozens of theorems **and named after him.**
.......
Should read as follows:

cauchy:
  born: 1789
  died: 1857
  name: Cauchy
  small: true
  bio: |
    __Augustin-Louis Cauchy__ (1789 – 1857) was a French mathematician and physicist. He contributed to a wide range of areas in mathematics, and
    dozens of theorems **are** named after him.

.....

cavalieri:
  name: Cavalieri
  born: 1598
  died: 1647
  bio: |
    __Bonaventura Cavalieri__ (1598 – 1647) was an Italian mathematician and monk. He developed a precursor to infinitesimal calculus, and is remembered
    for Cavalieri’s principle to find the volume of solids in geometry.

    Cavalieri also worked **optics and motion, introduction logarithms to Italy,**
    and exchanged many letters with Galileo Galilei.
  links:
    - title: Cavalieri’s Principle
      url: /course/circles/spheres-cones-cylinders#cavalieri

Should read as follows:

cavalieri:
  name: Cavalieri
  born: 1598
  died: 1647
  bio: |
    __Bonaventura Cavalieri__ (1598 – 1647) was an Italian mathematician and monk. He developed a precursor to infinitesimal calculus, and is remembered
    for Cavalieri’s principle to find the volume of solids in geometry.

    Cavalieri also worked **in** optics and motion, **introduced** logarithms to Italy,
    and exchanged many letters with Galileo Galilei.
  links:
    - title: Cavalieri’s Principle
      url: /course/circles/spheres-cones-cylinders#cavalieri

diophantus:
  born: 200
  died: 284
  name: Diophantus
  overflow: true
  bio: |
    __Diophantus__ was a Hellenistic mathematician who lived in Alexandria.
    Most of his works are about solving polynomial equations with several unknowns. These are now called **_Diophantine equation_** and remain an
    an important area of research today.

    It was while reading one of Diophantus’ books, many centuries later, that
    _Pierre de Fermat_ proposed one of these equations had no solution. This became known as “Fermat’s Last Theorem”, and was only solved in 1994.

Should read as follows:

diophantus:
  born: 200
  died: 284
  name: Diophantus
  overflow: true
  bio: |
    __Diophantus__ was a Hellenistic mathematician who lived in Alexandria.
    Most of his works are about solving polynomial equations with several unknowns. These are now called **_Diophantine equations_** and remain an
    an important area of research today.

    It was while reading one of Diophantus’ books, many centuries later, that
    _Pierre de Fermat_ proposed one of these equations had no solution. This became known as “Fermat’s Last Theorem”, and was only solved in 1994.

fuller:
  name: Fuller
  bio: __Richard Buckminster “Bucky” Fuller__ (1895 – 1983) was an American
    architect, designer and inventor. He is famous for constructing _geodesic
    dome_ – large, spherical structures. Similar looking **Carbon** molecules, the
    _fullerenes_, were later named after him.

Should read as follows:

fuller:
  name: Fuller
  **born: 1895**
  **died: 1983**
  bio: __Richard Buckminster “Bucky” Fuller__ (1895 – 1983) was an American
    architect, designer and inventor. He is famous for constructing _geodesic
    dome_ – large, spherical structures. Similar looking **carbon molecules**, the
    _fullerenes_, were later named after him.

galois:
  <snip>

    **While still in his teens, Galois proved that there is no general solution
    for polynomial equations of degree five or higher – simultaneously with
    Niels Abel.**

<snip>

At the age of 21, Galois was shot in a duel (some say a feud over a woman),
    and later died of his wounds. **In** the night before his death, he summarised
    his mathematical discoveries in a letter to a friend. It would take other mathematicians many years to fully realise the true impact of his work.

could read:

**While still in his teens, Galois, along with Niels Abel, proved that there is no general solution
    for polynomial equations of degree five or higher.**

<snip>

At the age of 21, Galois was shot in a duel (some say a feud over a woman),
    and later died of his wounds. **On** the night before his death, he summarised
    his mathematical discoveries in a letter to a friend. It would take other mathematicians many years to fully realise the true impact of his work.

planck:
  name: Plank
  bio: __Max Plank__ (1858 – 1947) was a German physicist and one of the
    original developers of Quantum Mechanics – for which received the Nobel
    Prize in 1918.

Should read as follows:

planck:
  name: Plank
 **born: 1858**
  **died: 1947**
  bio: __Max Plank__ (1858 – 1947) was a German physicist and one of the
    original developers of Quantum Mechanics – for which *he*( received the Nobel
    Prize in 1918.

**Comment by plegner** [comment]
Fixed in https://github.com/mathigon/textbooks/commit/d5e55727656502aae9de6d0267c0ba2a68c7c2e8. Note that we only include born/died keys for mathematicians that appear in the [timeline](https://mathigon.org/timeline), e.g. not physicists like Plank.

**Comment by jsuccari** [comment]
Makes sense. Thanks, @plegner
