### ISSUE TITLE
Prime checker display html tag

### ISSUE THREAD

**Issue by DegrangeM** [mathigon/textbooks#99]
https://mathigon.org/course/divisibility/distribution-of-primes

![image](https://user-images.githubusercontent.com/53106394/77915214-5af73500-7297-11ea-90e6-369b580278b5.png)

**Comment by DegrangeM** [comment]
(same with prime generator during loading)

**Comment by plegner** [comment]
Thanks, fixed in https://github.com/mathigon/textbooks/commit/813e5bae8f932139c6ce6bac4e2086b4f446ec65
